name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: "true"

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-20

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.7
        with:
          version: "20"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          # Make sure to set a version number!
          version: 4.0.14
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: "emsdk-cache"
          update: true

      - name: Verify
        run: emcc -v

      - name: Setup
        run: npm install

      # - name: Jest
      #   run: npm test

      # - name: Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     # files: ./coverage1.xml,./coverage2.xml # optional
      #     directory: ./coverage
      #     # flags: unittests # optional
      #     # name: codecov-umbrella # optional
      #     fail_ci_if_error: true
      #     # verbose: true # optional (default = false)

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@p2party"

      # - name: Publish on github
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
